### ISSUE TITLE
Colour blind friendly charts

### ISSUE THREAD

**Issue by mrjoh3** [djpr-data/djprlabourdash#153]
should be resolved by https://github.com/djpr-data/djprtheme/issues/23 and https://github.com/djpr-data/djprshiny/issues/22

After issues above finished need to check outcome in dashboards

**Comment by annett-djpr** [comment]
can be closed pending approval of PR: https://github.com/djpr-data/djprlabourdash/pull/156

**Comment by annett-djpr** [comment]
PR approved, issue closed.
