### ISSUE TITLE
Add disclaimer on github

### ISSUE THREAD

**Issue by annett-djpr** [djpr-data/djprlabourdash#181]
Legal:

Disclaimer – we suggest the following disclaimer wording be adopted and are happy for you to use this wording as a disclaimer on the github landing page too.

“Disclaimer

The content of this github repository is provided for information purposes only.  No claim is made as to the accuracy or currency of any of the content on this website at any time. 
The Victorian Government and this agency (the Department of Jobs, Precincts and Regions) do not accept any liability to any person for the information (or the use of such information) which is provided on this website, including information sourced or derived from third parties or incorporated into the website by reference.”

**Comment by annett-djpr** [comment]
Maybe this could be done as a ReadMe file on the highest level of our gihub?

**Comment by Henry-DJPR** [comment]
I'm apprehensive to put this disclaimer on the github as it deviates from the standard opensource license (MIT). Custom licenses can make open source a bit more difficult. I believe that the MIT should cover these bases anyway

**Comment by annett-djpr** [comment]
Can we close this one?

**Comment by Henry-DJPR** [comment]
Yep
