### ISSUE TITLE
Do we need an accessibility disclaimer?

### ISSUE THREAD

**Issue by annett-djpr** [djpr-data/djprlabourdash#184]
For us to consider whether we want to or need to put this on the dashboard. Can we promise these things?

From legal:

Accessibility – we suggest the following disclaimer wording be used on the dashboard webpages:
“If you would like to receive this publication in an accessible format, such as large print or audio, telephone (insert department telephone) or email [insert contact details]”

**Comment by Henry-DJPR** [comment]
fixed in dev
