### ISSUE TITLE
Create link on bottom of each page to the disclaimer and copyright bits on Legal page

### ISSUE THREAD

**Issue by annett-djpr** [djpr-data/djprlabourdash#190]

**Comment by mrjoh3** [comment]
this is achieved using a combo of `shiny::actionLink` in the UI and `` in the server.

```
# in UI
shiny::actionLink(id = 'to_legal', label = NULL, icon = NULL, 'Legal Statements')


# in server 
  observeEvent(input$to_legal, {
    shinydashboard::updateTabItems(session,
                                   "tabs",
                                   selected = "legal")
```

the trick here is you need a unique id for each `actionLink` . Then in the server `observeEvent` you need to include all of those unique names.

@annett-djpr  lets discuss merging with current footer tomorrow

**Comment by annett-djpr** [comment]
Fixed in https://github.com/djpr-data/djprlabourdash/tree/issue190_legal_links_annett.
