### ISSUE TITLE
Add 'Aboriginal' definition statement to bottom of Aboriginal page

### ISSUE THREAD

**Issue by annett-djpr** [djpr-data/djprlabourdash#199]
Suggested by Comms (but might be amended post resolution of issue #197):

"We recognise the diversity of Aboriginal people living in Victoria. We use the term ‘Aboriginal Victorians’ to include Victorian Traditional Owners, clans, family groups, and all other Aboriginal and Torres Strait Islander descendants living in Victoria."

Do we want to add that definition to the Methodology page as well?

**Comment by Emma-DJPR** [comment]
Maybe on the glossary page

**Comment by annett-djpr** [comment]
The glossary is on the Methodology page - do you mean that?

**Comment by Emma-DJPR** [comment]
Matt suggested at the bottom of the page should be enough.

**Comment by annett-djpr** [comment]
Still needs to be done. Will close once it is done. I think you meant to close the other issue.

**Comment by annett-djpr** [comment]
Issue solved in https://github.com/djpr-data/djprlabourdash/pull/202.
