### ISSUE TITLE
update COVID to COVID-19

### ISSUE THREAD

**Issue by mrjoh3** [djpr-data/djprlabourdash#207]
the state gov style guide requires use of the complete term `COVID-19` please update every mention of `COVID` across the dashboard and update to `COVID-19`. This will include all headers, column headings captions and footers.

**Comment by annett-djpr** [comment]
to be fixed in https://github.com/djpr-data/djprlabourdash/tree/covid19_fix_annett

**Comment by annett-djpr** [comment]
done, just waiting for PR to be approved.
